jobs:
  include:
    - language: node_js
      node:
        - 12
      before_script:
        - cd frontend
      script:
        - npm install
        - npm run build
    - language: go
      go:
        - 1.x

